package Mapping;
// Generated Oct 15, 2017 5:24:28 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import org.hibernate.annotations.GenericGenerator;


/**
 * Role generated by hbm2java
 */
@Entity
public class Role implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "generator", strategy = "increment")
    @GeneratedValue(generator = "generator")
    private int roleid;
    private String title;

    public Role() {
    }

    public Role(int roleid) {
        this.roleid = roleid;
    }

    public Role(int roleid, String title) {
        this.roleid = roleid;
        this.title = title;
    }

    public int getRoleid() {
        return this.roleid;
    }

    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
